document.addEventListener('DOMContentLoaded',()=>{
  const actions=document.querySelector('.nav-actions');
  if(!actions||document.getElementById('loginBtn'))return;
  const style=document.createElement('style');
  style.textContent=`
    .login-nav-btn{border:0;border-radius:14px;padding:10px 16px;background:linear-gradient(135deg,#168c8c,#f08a24);color:#fff;font-family:inherit;font-weight:800;font-size:12px;box-shadow:0 8px 22px rgba(22,140,140,.18);cursor:pointer;transition:.2s;white-space:nowrap}.login-nav-btn:hover{transform:translateY(-2px);box-shadow:0 12px 28px rgba(22,140,140,.25)}
    .login-modal{display:none;position:fixed;inset:0;z-index:6000;background:rgba(16,42,67,.58);backdrop-filter:blur(5px);place-items:center;padding:18px}.login-modal.show{display:grid}.login-box{width:min(430px,100%);background:#fff;border-radius:28px;padding:30px;position:relative;box-shadow:0 30px 90px rgba(16,42,67,.28);text-align:right}.login-close{position:absolute;top:12px;left:16px;border:0;background:transparent;font-size:28px;color:#71808b;cursor:pointer}.login-logo{width:58px;height:58px;border-radius:18px;display:grid;place-items:center;background:linear-gradient(135deg,#168c8c,#f08a24);font-size:30px;margin-bottom:12px}.login-box h2{margin:0 0 6px;color:#102a43;font-size:25px}.login-box>p{margin:0 0 20px;color:#627d98;font-size:12px}.login-field{margin:12px 0}.login-field label{display:block;font-size:11px;font-weight:800;color:#102a43;margin-bottom:6px}.login-field input{width:100%;padding:13px 14px;border:1px solid #dfe9ec;border-radius:13px;outline:0;font-family:inherit;font-size:13px}.login-field input:focus{border-color:#168c8c;box-shadow:0 0 0 3px rgba(22,140,140,.1)}.login-submit{width:100%;margin-top:10px;padding:13px;border:0;border-radius:13px;background:#168c8c;color:#fff;font-family:inherit;font-weight:800;cursor:pointer}.login-extra{display:flex;justify-content:space-between;align-items:center;margin:12px 0;color:#71808b;font-size:10px}.login-extra button{border:0;background:none;color:#168c8c;font-weight:800;cursor:pointer}.login-demo{margin-top:15px;background:#f4f9fa;border-radius:13px;padding:10px;color:#627d98;font-size:10px;text-align:center}.logged-user{display:none;align-items:center;gap:7px;border:1px solid #dce7ec;background:#fff;border-radius:14px;padding:8px 11px;color:#102a43;font-weight:800;font-family:inherit;font-size:11px;cursor:pointer}.logged-user.show{display:flex}.logged-user span{width:27px;height:27px;border-radius:50%;display:grid;place-items:center;background:#eaf7f7;color:#168c8c}
    @media(max-width:760px){.login-nav-btn{padding:9px 11px;font-size:10px}.logged-user{padding:7px}.logged-user strong{display:none}}
  `;
  document.head.appendChild(style);
  const btn=document.createElement('button');btn.id='loginBtn';btn.className='login-nav-btn';btn.innerHTML='👤 تسجيل الدخول';btn.setAttribute('aria-label','تسجيل الدخول');
  const user=document.createElement('button');user.id='loggedUser';user.className='logged-user';user.innerHTML='<span>👤</span><strong>حسابي</strong>';user.setAttribute('aria-label','حسابي');
  actions.insertBefore(btn,actions.firstChild);actions.insertBefore(user,actions.firstChild);
  const modal=document.createElement('div');modal.className='login-modal';modal.id='loginModal';modal.innerHTML=`<div class="login-box" role="dialog" aria-modal="true" aria-labelledby="loginTitle"><button class="login-close" id="loginClose" aria-label="إغلاق">×</button><div class="login-logo">🚌</div><h2 id="loginTitle">أهلاً بيك في وصلني 👋</h2><p>سجلي دخولك عشان تتابعي رحلاتك ومحفظتك والمفضلة بسهولة.</p><form id="loginForm"><div class="login-field"><label for="loginEmail">البريد الإلكتروني</label><input id="loginEmail" type="email" placeholder="example@email.com" required></div><div class="login-field"><label for="loginPassword">كلمة المرور</label><input id="loginPassword" type="password" placeholder="••••••••" required minlength="4"></div><div class="login-extra"><label><input type="checkbox" id="rememberLogin"> تذكرني</label><button type="button" id="forgotLogin">نسيت كلمة المرور؟</button></div><button class="login-submit" type="submit">دخول إلى حسابي</button></form><div class="login-demo">✨ وضع تجريبي: البيانات لا تُرسل إلى خادم حقيقي.</div></div>`;document.body.appendChild(modal);
  const close=()=>modal.classList.remove('show');
  btn.addEventListener('click',()=>modal.classList.add('show'));document.getElementById('loginClose').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});
  document.getElementById('forgotLogin').addEventListener('click',()=>alert('ميزة استعادة كلمة المرور تجريبية في نسخة الـMVP.'));
  document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('waslniLoggedIn','1');localStorage.setItem('waslniUserEmail',document.getElementById('loginEmail').value);close();setLoggedState();if(typeof toast==='function')toast('تم تسجيل الدخول بنجاح 👋');});
  user.addEventListener('click',()=>{if(confirm('تسجيل الخروج من الحساب التجريبي؟')){localStorage.removeItem('waslniLoggedIn');localStorage.removeItem('waslniUserEmail');setLoggedState();if(typeof toast==='function')toast('تم تسجيل الخروج');}});
  function setLoggedState(){const logged=localStorage.getItem('waslniLoggedIn')==='1';btn.style.display=logged?'none':'block';user.classList.toggle('show',logged);}
  setLoggedState();
});
